---
name: Config

permissions: {}

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      platforms:
        description: The platforms to build (JSON array string)
        default: >-
          ["linux/amd64","linux/arm/v6","linux/arm/v7","linux/arm64","linux/ppc64le","linux/riscv64","linux/s390x"]
        required: false
        type: string
    outputs:
      container_version:
        description: The container version from src/version.txt
        value: ${{ jobs.config.outputs.container_version }}
      image_name:
        description: The container image name
        value: felddy/weewx
      platforms:
        description: The platforms to build (JSON array string)
        value: ${{ inputs.platforms }}
      test_platforms:
        description: The platform to use for testing (JSON array string)
        value: '["linux/amd64"]'

jobs:
  config:
    name: Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      container_version: ${{ steps.version.outputs.container_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # tag=v7.0.0
      - name: Emit version outputs
        id: version
        run: make github-output >> "$GITHUB_OUTPUT"
