---

name: Labels

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read  # for actions/checkout to fetch code
      issues: write  # for crazy-max/ghaction-github-labeler to create, rename, update and delete label
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@77450f9fa47c41fbab15c0923417fff00730ffa3
