---
name: sync-labels

on:
  push:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      # actions/checkout needs this to fetch code
      contents: read
      # crazy-max/ghaction-github-labeler needs this to manage repository labels
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # tag=v2.19.4
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # tag=v6.0.3
      - name: Sync repository labels
        if: success()
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d  # tag=v6.0.0
        with:
          # This is a hideous ternary equivalent so we only do a dry run unless
          # this workflow is triggered by the develop branch.
          dry-run: ${{ github.ref_name == 'develop' && 'false' || 'true' }}
